server {
    listen 80;
    server_name  dict.hsb.kr;
    root   /usr/share/nginx/html;  # React 빌드 파일이 위치한 경로

    index  index.html index.htm;

    location /api/ {
        proxy_pass http://dict-server;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host dict-server;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
